synth: synth.c
	cl.exe synth.c

lualib: lualib.c
	cl.exe /LD lualib.c /link "%LUA_DEV%\lua.lib"
	MOVE /Y lualib.dll audio
   	DEL lualib.exp 
	DEL lualib.lib 
	DEL lualib.obj 

lua: lualib.c
	luac5.4.2.exe tst.lua

mediaPlayer: mediaPlayer.c
	cl.exe mediaPlayer.c
